apiVersion: v1
kind: Service

metadata:
  name: onlineshop-service
  namespace: onlineshop

spec:
  selector:
    app: onlineshop

  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080

  type: NodePort
